version: '2'
services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: keno
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        container_name: test_keno_game_db
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    app:
        build: .
        container_name: test_keno_game
        ports: 
          - "9999:9999"
        depends_on:
          - db